name: End To End Tests

on: [push]

jobs:
  jest:
    name: "Jest"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: npx jest **/*.spec.js
  prettier:
    name: "Prettier"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: npx prettier --check **/*.js
  install:
    name: "Test Installation"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: ./install.sh
      - run: wflow
  npm-install:
    name: "Test NPM Installation"
    runs-on: ubuntu-latest
    steps:
      - run: |
          sudo npm install -g wflow;
          git clone https://github.com/phishy/wflow.git;
          cd wflow;
          wflow
